# Generated by Django 6.0.4 on 2026-05-11 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(default='USER', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('user_role', models.CharField(choices=[('photographer', 'Photographer'), ('client', 'Client')], default='client', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('document_type', models.CharField(choices=[('Citizenship', 'Citizenship Card'), ('national_id', 'National ID'), ('passport', 'Passport'), ('driving_License', 'Driving License')], max_length=60, null=True)),
                ('document_number', models.CharField(max_length=25, null=True)),
                ('issued_district', models.CharField(max_length=30, null=True)),
                ('permanent_address', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_pictures')),
                ('citizenship_front', models.ImageField(blank=True, null=True, upload_to='citizenship')),
                ('citizenship_back', models.ImageField(blank=True, null=True, upload_to='citizenship')),
                ('kyc_verified', models.CharField(choices=[('not_verified', 'Not verified'), ('in_review', 'In review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_verified')),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone', models.CharField(max_length=10, null=True)),
                ('price_charge', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(choices=[('rs', 'RS'), ('Dollor', '$')], max_length=10, null=True)),
                ('no_of_cameras', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=150, null=True)),
                ('intrest', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
