# Generated by Django 6.0.4 on 2026-04-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_myuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_role',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
