# Generated by Django 6.0.4 on 2026-05-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myuser_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='full_name',
            field=models.CharField(default='USER', max_length=100),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_role',
            field=models.CharField(choices=[('photographer', 'Photographer'), ('client', 'Client')], default='client', max_length=20),
        ),
    ]
