# Generated by Django 6.0.4 on 2026-05-03 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_myuser_full_name_alter_myuser_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('date_of_birth', models.DateField()),
                ('document_type', models.CharField(max_length=60)),
                ('document_number', models.CharField(max_length=25)),
                ('issued_district', models.CharField(max_length=30)),
                ('permanent_address', models.CharField(max_length=100)),
                ('citizenship_front', models.ImageField(blank=True, null=True, upload_to='citizenship')),
                ('citizenship_back', models.ImageField(blank=True, null=True, upload_to='citizenship')),
                ('kyc_verified', models.CharField(choices=[('not_varified', 'Not varified'), ('in_review', 'In review'), ('varified', 'Varified'), ('rejected', 'Rejected')], default='not_varified')),
                ('rejection_reason', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
