# Generated by Django 6.0.4 on 2026-05-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
