# Generated by Django 6.0.4 on 2026-05-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_profile_photo_profile_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='document_type',
            field=models.CharField(choices=[('Citizenship', 'Citizenship Card'), ('national_id', 'National ID'), ('passport', 'Passport'), ('driving_License', 'Driving License')], max_length=60, null=True),
        ),
    ]
