# Generated by Django 6.0.4 on 2026-05-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_myuser_groups_myuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kyc_verified',
            field=models.CharField(choices=[('not_verified', 'Not verified'), ('in_review', 'In review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_verified'),
        ),
    ]
