# Generated by Django 6.0.4 on 2026-05-16 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photographer', models.EmailField(max_length=254)),
                ('client', models.EmailField(max_length=254)),
                ('price', models.PositiveIntegerField()),
                ('date_of_booking', models.DateField()),
                ('Accessories', models.CharField(max_length=100)),
                ('cameras', models.PositiveIntegerField()),
                ('staff', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=10)),
                ('drone', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.package')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('client', 'package'), name='unique_client_package')],
            },
        ),
    ]
